l = int(input("Enter length : "))
b = int(input("Enter breadth : "))
r = int(input("Enter radius : "))
print("Rectangle :-")
print("Area :", l*b)
print("Perimeter :", 2*(l+b))
print("Circle :-")
print("Area :", 3.14*r*r)
print("Perimeter :", 2*3.14*r)