s1 = int(input("Enter marks : "))
s2 = int(input("Enter marks : "))
s3 = int(input("Enter marks : "))
s4 = int(input("Enter marks : "))
s5 = int(input("Enter marks : "))
s6 = int(input("Enter marks : "))
sum = (s1+s2+s3+s4+s5+s6)
print("Sum :",sum)
print("Percentage :",(sum/600)*100)
